//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int Id { get; set; }
        public int uid { get; set; }
        public bool like { get; set; }
        public int pid { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
