//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostFile
    {
        public int Id { get; set; }
        public string file_name { get; set; }
        public string file_type { get; set; }
        public byte[] file_content { get; set; }
        public int ref_id { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
